#!/bin/bash
### BEGIN INIT INFO
# Provides:          mailcatcher
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

PID_FILE=/var/run/mailcatcher.pid
NAME=mailcatcher
PROG=/usr/local/bin/mailcatcher
USER=root
GROUP=root

start() {
	echo -n "Starting MailCatcher"
	if start-stop-daemon --stop --quiet --pidfile $PID_FILE --signal 0
	then
		echo " already running."
		exit
	fi
	start-stop-daemon \
		--start \
		--pidfile $PID_FILE \
		--make-pidfile \
		--background \
		--exec $PROG \
		--user $USER \
		--group $GROUP \
		--chuid $USER \
		-- \
		--foreground \
		--http-ip 0.0.0.0 \
		--no-quit \
	echo "."
	return $?
}

stop() {
	echo -n "Stopping MailCatcher"
	start-stop-daemon \
		--stop \
		--oknodo \
		--pidfile $PID_FILE
	echo "."
	return $?
}

restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac
