default[:vccw][:src_path] = "/usr/local/share"
default[:vccw][:makepot] = "/usr/bin/php /usr/local/share/wp-i18n/makepot.php"
default[:vccw][:bash_profile] = "/home/vagrant/.bash_profile"
default[:vccw][:i18ntools_repositry] = "http://i18n.svn.wordpress.org/tools/trunk/"
default[:vccw][:hatamoto_repository] = "https://github.com/megumiteam/hatamoto.git"
default[:vccw][:iemoto_repositry] = "https://github.com/megumiteam/iemoto.git"
default[:vccw][:phpunit] = 'https://phar.phpunit.de/phpunit.phar'
default[:vccw][:phpunit_link] = '/usr/bin/phpunit'
default[:vccw][:test][:wp_test_install] = '/usr/bin/wp-test-install'
default[:vccw][:test][:mysql_name] = 'wp-test'
default[:vccw][:test][:mysql_user] = 'root'
default[:vccw][:test][:mysql_pass] = ''
default[:vccw][:test][:mysql_host] = 'localhost'
default[:vccw][:test][:wp_version] = 'latest'
