default[:vccw][:path] = "/usr/share/wp-i18n"
default[:vccw][:makepot] = "/usr/bin/php /usr/share/wp-i18n/makepot.php"
default[:vccw][:bash_profile] = "/home/vagrant/.bash_profile"
default[:vccw][:i18ntools_repositry] = "http://i18n.svn.wordpress.org/tools/trunk/"
default[:vccw][:hatamoto_repository] = "https://github.com/megumiteam/hatamoto.git"
default[:vccw][:iemoto_repositry] = "https://github.com/megumiteam/iemoto.git"
