default['wp-plugins']['url'] = ""
default['wp-plugins']['title'] = "Welcome to the Vagrant"
default['wp-plugins']['admin_user'] = "admin"
default['wp-plugins']['admin_password'] = "admin"
default['wp-plugins']['admin_email'] = "vagrant@example.com"
